#!/usr/bin/env python3
"""prolo - ein Befehl fuer die ganze ProloWelt.  Hilfe:  prolo -h

Der Code liegt in kern/. Diese Datei findet ihn auch dann, wenn sie ueber
den Verweis /usr/local/bin/prolo aufgerufen wird.
"""
import os
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from kern.cli import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
